### ISSUE TITLE
Text issue with SMX

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/TheGoldStandard#12]
Text issue with Stockalike Mining Expansion (SMX) parts

Also notice - : 0.30/sec which is in that format for all SMX parts.

![image](https://user-images.githubusercontent.com/39887717/133194550-111c44ee-eb9b-4e4e-b6fe-c08b1351ebdf.png)

by [Krzeszny](https://forum.kerbalspaceprogram.com/index.php?/profile/203780-krzeszny/)
@Krzeszny

**Comment by zer0Kerbal** [comment]
@Krzeszny - Please elaborate on the `0.30/sec which is in that format for all SMX parts`?

**Comment by zer0Kerbal** [comment]
- [StockalikeMiningExpansion.cfg]
  - removed extra `#` graffiti making the localization tags start with `##`, ran out of whiteout...

**Comment by Krzeszny** [comment]
> @Krzeszny - Please elaborate on the `0.30/sec which is in that format for all SMX parts`?

It says
'- [nothing]: 0.30/sec' while it should be '- Ore: 0.30/sec'

**Comment by zer0Kerbal** [comment]
> > @Krzeszny - Please elaborate on the `0.30/sec which is in that format for all SMX parts`?
> 
> It says `- : 0.30/sec` while it should be `- [ore type]: 0.30/sec`

Thank you @Krzeszny, I will look into it. 🔭 👁️‍🗨️
