### ISSUE TITLE
Localization - Mexican (Mexicano) <es-mx.cfg> 

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/TheGoldStandard#43]
# Localization - Mexican (Mexicano) <es-mx.cfg>

### GameData

- [x] add es-mx.cfg 

### Translation

- [x] [![Mexicano][ME]][ME] [Mexican (Mexicano)][ME] <es-mx.cfg>  

[ME]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Mexican-flag-sm.png "Mexicano" 

### Update Documentation

- [x]  mod Readme 🔢 
- [x]  releaseNotes.md 🧾 

### GitHub Issues

- [x] assign to zer0Kerbal
- [x] assign projects (user and repo)
- [x] assign label: Localization
- [x] assign label: help-wanted
- [x] assign milestone: Localization - [Mexican (Mexicano)][ME] <es-mx.cfg>

### Update Social Media

- [x] CurseForge
- [x] CKAN
- [x] Forum
- [x] GitHub
- [x] Patreon
- [x] Reddit
- [x] SpaceDock

### Wiki

- [ ] update localization list 
  

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization" 
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

**Comment by JamesErvin-5** [comment]
I've opened a pull request and issue.
